# Generated by Django 4.2.20 on 2025-04-13 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre de la agencia')),
                ('nombreClave', models.CharField(max_length=15, unique=True, verbose_name='Nombre clave')),
                ('ciudad', models.CharField(max_length=20, verbose_name='Ciudad')),
            ],
            options={
                'verbose_name': 'Agencia',
                'verbose_name_plural': 'Agencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre Completo')),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('tieneSCTR', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('ppto', models.CharField(max_length=10, unique=True)),
                ('codigoDelServicio', models.CharField(default='SIN CODIGO', max_length=10, unique=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_EJECUCION', 'En ejecución'), ('ATENDIDO', 'Atendido')], default='NUEVO', max_length=20, verbose_name='Estado de la cotización')),
                ('costo', models.FloatField(default=0)),
                ('agencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.agencia', verbose_name='Agencia')),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Clave única')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la cuenta')),
                ('referencias', models.TextField(default='[]', null=True)),
            ],
            options={
                'verbose_name': 'Cuenta',
                'verbose_name_plural': 'Cuentas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20, unique=True, verbose_name='Clave única')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre de la empresa')),
                ('tipoTicket', models.CharField(max_length=10, verbose_name='Tipo de ticket')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre completo')),
                ('nombreClave', models.CharField(max_length=20, verbose_name='Nombre clave')),
                ('correo', models.CharField(max_length=20, verbose_name='Correo electrónico')),
                ('cuentaDefault', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cuenta', verbose_name='Cuenta')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspectores', to='main.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Inspector',
                'verbose_name_plural': 'Inspectores',
                'ordering': ['nombre'],
            },
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.AddField(
            model_name='cuenta',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='main.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.inspector', verbose_name='Inspector'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Agencias', to='main.cuenta', verbose_name='Cuenta'),
        ),
        migrations.AddField(
            model_name='agencia',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencias', to='main.empresa', verbose_name='Empresa'),
        ),
    ]
