# Generated by Django 4.2.20 on 2025-04-13 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_agencia_referencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencia',
            old_name='nombreClave',
            new_name='key',
        ),
    ]
