# Generated by Django 4.2.20 on 2025-04-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_nombreclave_agencia_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspector',
            name='isFemale',
            field=models.BooleanField(default=False, verbose_name='Sexo femenino'),
        ),
    ]
